import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class choosepatient extends javax.swing.JFrame {

    java.util.Date date1;
    java.sql.Date sqldate;
    String timey = null;
    String dname;

    public choosepatient() {
        initComponents();
        showTableData();
        setResizable(false);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        apTable.setDefaultRenderer(String.class, centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DRNAME = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        time = new javax.swing.JComboBox();
        dASearchbtn1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        apTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Set Appointment");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-small.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        panel2.setBackground(new java.awt.Color(255, 255, 255,120));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 55, 255));
        jLabel12.setText("Set Appointment");

        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 340, 70));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 55, 255));
        jLabel11.setText("PATIENT ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 50));

        DRNAME.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        DRNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DRNAMEActionPerformed(evt);
            }
        });
        DRNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DRNAMEKeyReleased(evt);
            }
        });
        jPanel1.add(DRNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 530, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-small.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, -1, 50));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 55, 255));
        jLabel2.setText("Date");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 70, 37));

        date.setBackground(new java.awt.Color(255, 255, 255));
        date.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));
        date.setDateFormatString("dd MMM, yyyy");
        date.setMinSelectableDate(new Date());
        date.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 280, 40));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 55, 255));
        jLabel3.setText("Timing");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, 40));

        time.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Time", "12:00 PM", "01:00 PM", "02:00 PM", "03:00 PM", "04:00 PM", "05:00 PM", "07:00 PM", "08:00 PM", "09:00 PM", "10:00 PM", "11:00 PM", "12:00 AM", " " }));
        time.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));
        time.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 280, 40));

        dASearchbtn1.setBackground(new java.awt.Color(255, 255, 255));
        dASearchbtn1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dASearchbtn1.setForeground(new java.awt.Color(0, 102, 255));
        dASearchbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next-btn.png"))); // NOI18N
        dASearchbtn1.setBorder(null);
        dASearchbtn1.setBorderPainted(false);
        dASearchbtn1.setContentAreaFilled(false);
        dASearchbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dASearchbtn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next-small.png"))); // NOI18N
        dASearchbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dASearchbtn1MouseClicked(evt);
            }
        });
        dASearchbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dASearchbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(dASearchbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, 260, 90));

        apTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Surname", "Age", "Marital Status", "Gender", "Address", "Aadhaar No.", "Phoneno", "Patient Type", "Date", "Bed No."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        apTable.getTableHeader().setResizingAllowed(false);
        apTable.getTableHeader().setReorderingAllowed(false);
        apTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(apTable);
        if (apTable.getColumnModel().getColumnCount() > 0) {
            apTable.getColumnModel().getColumn(0).setResizable(false);
            apTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            apTable.getColumnModel().getColumn(1).setResizable(false);
            apTable.getColumnModel().getColumn(1).setPreferredWidth(210);
            apTable.getColumnModel().getColumn(2).setResizable(false);
            apTable.getColumnModel().getColumn(2).setPreferredWidth(210);
            apTable.getColumnModel().getColumn(3).setResizable(false);
            apTable.getColumnModel().getColumn(3).setPreferredWidth(80);
            apTable.getColumnModel().getColumn(4).setResizable(false);
            apTable.getColumnModel().getColumn(4).setPreferredWidth(180);
            apTable.getColumnModel().getColumn(5).setResizable(false);
            apTable.getColumnModel().getColumn(5).setPreferredWidth(150);
            apTable.getColumnModel().getColumn(6).setResizable(false);
            apTable.getColumnModel().getColumn(6).setPreferredWidth(220);
            apTable.getColumnModel().getColumn(7).setResizable(false);
            apTable.getColumnModel().getColumn(7).setPreferredWidth(210);
            apTable.getColumnModel().getColumn(8).setResizable(false);
            apTable.getColumnModel().getColumn(8).setPreferredWidth(180);
            apTable.getColumnModel().getColumn(9).setResizable(false);
            apTable.getColumnModel().getColumn(9).setPreferredWidth(210);
            apTable.getColumnModel().getColumn(10).setResizable(false);
            apTable.getColumnModel().getColumn(10).setPreferredWidth(160);
            apTable.getColumnModel().getColumn(11).setResizable(false);
            apTable.getColumnModel().getColumn(11).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1240, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/appointment.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked

    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked

    }//GEN-LAST:event_jLabel19MouseClicked

    private void dASearchbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dASearchbtn1MouseClicked

    }//GEN-LAST:event_dASearchbtn1MouseClicked

    private void dASearchbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dASearchbtn1ActionPerformed
        int row = apTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Please fill all details!");
        }
        String pname1 = (apTable.getValueAt(row, 1).toString());
        String pname2 = (apTable.getValueAt(row, 2).toString());
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalmanagementsystem?useSSL=false", "root", "");
            PreparedStatement pst = conn.prepareStatement("insert into appointment" + "(dname,pname,pname2,date,time)" + " values(?,?,?,?,?)");
            date1 = date.getDate();
            if (date1 != null) {
                sqldate = new java.sql.Date(date1.getTime());
            }
            if (time.getSelectedItem()!=null){
                timey = time.getSelectedItem().toString();
            }

            if (sqldate == null || "Choose Time".equals(timey)) {

                JOptionPane.showMessageDialog(null, "Please fill date or time!");
            } else {
                pst.setString(1, dname);
                pst.setString(2, pname1);
                pst.setString(3, pname2);
                pst.setDate(4, sqldate);
                pst.setString(5, timey);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "PATIENT " + pname1 + "  " + pname2 + " Appointmented with DOCTOR  " + dname + " On  " + sqldate + " At  " + timey);
                date.setDate(null);
                time.setSelectedIndex(0);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_dASearchbtn1ActionPerformed
    public void showTableData() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalmanagementsystem?useSSL=false", "root", "");
            PreparedStatement pst = conn.prepareStatement("SELECT * FROM hospitalmanagementsystem.patient");
            ResultSet rs = pst.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) apTable.getModel();
            tm.setRowCount(0);
            while (rs.next()) {
                Object o[] = {
                    rs.getString("P_id"),
                    rs.getString("FirstName"),
                    rs.getString("SecondName"),
                    rs.getString("Age"),
                    rs.getString("MaritialStatus"),
                    rs.getString("Gender"),
                    rs.getString("Address"),
                    rs.getString("Aadhaar"),
                    rs.getString("phoneno"),
                    rs.getString("PatientType"),
                    rs.getString("Date"),
                    rs.getString("BedNo")
                };
                tm.addRow(o);
            }
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void apTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apTableMouseClicked
        int SelectedRow = apTable.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel) apTable.getModel();

    }//GEN-LAST:event_apTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ReceptionitActivity ra = new ReceptionitActivity();
        ra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DRNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DRNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DRNAMEActionPerformed

    private void DRNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DRNAMEKeyReleased
        DefaultTableModel table = (DefaultTableModel) apTable.getModel();
        String search1 = DRNAME.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        apTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search1));
        showTableData();
    }//GEN-LAST:event_DRNAMEKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalmanagementsystem?useSSL=false", "root", "");
            PreparedStatement pst = conn.prepareStatement("SELECT * FROM hospitalmanagementsystem.patient where P_id=?");
            pst.setString(1, DRNAME.getText());
            ResultSet rs = pst.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) apTable.getModel();
            tm.setRowCount(0);
            while (rs.next()) {
                Object o[] = {
                    rs.getString("P_id"),
                    rs.getString("FirstName"),
                    rs.getString("SecondName"),
                    rs.getString("Age"),
                    rs.getString("MaritialStatus"),
                    rs.getString("Gender"),
                    rs.getString("Address"),
                    rs.getString("Aadhaar"),
                    rs.getString("PatientType"),
                    rs.getString("Date"),
                    rs.getString("phoneno"),
                    rs.getString("BedNo")
                };
                tm.addRow(o);
            }
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choosepatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choosepatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choosepatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choosepatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choosepatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DRNAME;
    private javax.swing.JTable apTable;
    private javax.swing.JButton dASearchbtn1;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel2;
    private javax.swing.JComboBox time;
    // End of variables declaration//GEN-END:variables
}
