import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class medicinedetails1 extends javax.swing.JFrame {

    public medicinedetails1() {
        initComponents();
        panel2.setBackground(new Color(255, 255, 255, 120));
        showTableData();
        setResizable(false);
        jButton9.setEnabled(false);
        setTitle("Pharmacist");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        ref2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        name2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        dose2 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        issue2 = new javax.swing.JTextField();
        dd2 = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        expiry2 = new javax.swing.JTextField();
        compony2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        advice2 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        sideeffects2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        depttable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back-small.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 60));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-med-btn.png"))); // NOI18N
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.blue));
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-med-btn-small.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 150, 80));

        jButton9.setBackground(new java.awt.Color(0, 51, 255));
        jButton9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update-med-btn.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update-med-btn-small.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 150, 80));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-med-btn.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-med-btn-small.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 170, 80));

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit-med-btn.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit-med-btn-small.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 150, 80));

        panel2.setBackground(new java.awt.Color(255, 255, 255, 120));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("MEDICINE DETAILS");
        panel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 340, 80));

        jPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1280, 80));

        jLabel36.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel36.setText("Ref#");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, 30));

        ref2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ref2refActionPerformed(evt);
            }
        });
        jPanel1.add(ref2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 240, 35));

        jLabel35.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel35.setText("Table Name");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, 30));

        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2nameActionPerformed(evt);
            }
        });
        jPanel1.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 240, 32));

        jLabel38.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel38.setText("Dose(mg)");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 105, 30));

        dose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dose2doseActionPerformed(evt);
            }
        });
        jPanel1.add(dose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 180, 240, 32));

        jLabel39.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel39.setText("Possible SideEffects");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, 30));

        jLabel43.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel43.setText("Company name");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, 30));

        jLabel42.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel42.setText("Storage Advice");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, 30));

        issue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue2issueActionPerformed(evt);
            }
        });
        jPanel1.add(issue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 220, 240, 32));

        dd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dd2ddActionPerformed(evt);
            }
        });
        jPanel1.add(dd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, 240, 32));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricecomponyActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 240, 32));

        expiry2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiry2expiryActionPerformed(evt);
            }
        });
        jPanel1.add(expiry2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 240, 32));

        compony2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compony2componyActionPerformed(evt);
            }
        });
        jPanel1.add(compony2, new org.netbeans.lib.awtextra.AbsoluteConstraints(949, 260, 240, 32));

        jLabel40.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel40.setText("Issue Date");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 105, 30));

        jLabel37.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel37.setText("Daily Dose");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 130, 30));

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityadviceActionPerformed(evt);
            }
        });
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(949, 300, 240, 32));

        advice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advice2adviceActionPerformed(evt);
            }
        });
        jPanel1.add(advice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 300, 240, 32));

        jLabel44.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel44.setText("Price ");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, 30));

        sideeffects2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideeffects2sideeffectsActionPerformed(evt);
            }
        });
        jPanel1.add(sideeffects2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 240, 32));

        jLabel41.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel41.setText("Expiry Date");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 130, 30));

        jLabel45.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel45.setText("Quantity Avaliable");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 200, 30));

        depttable.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        depttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tablet Name", "Daily Dose", "Ref#", "Dose (mg)", "Possible Side Effect", "Issue Date", "Expiry Date", "Company", "Storage Advise", "Price", "Quantity Available"
            }
        ));
        depttable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        depttable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        depttable.getTableHeader().setResizingAllowed(false);
        depttable.getTableHeader().setReorderingAllowed(false);
        depttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depttableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(depttable);
        if (depttable.getColumnModel().getColumnCount() > 0) {
            depttable.getColumnModel().getColumn(0).setResizable(false);
            depttable.getColumnModel().getColumn(0).setPreferredWidth(100);
            depttable.getColumnModel().getColumn(1).setResizable(false);
            depttable.getColumnModel().getColumn(1).setPreferredWidth(100);
            depttable.getColumnModel().getColumn(2).setResizable(false);
            depttable.getColumnModel().getColumn(2).setPreferredWidth(100);
            depttable.getColumnModel().getColumn(3).setResizable(false);
            depttable.getColumnModel().getColumn(3).setPreferredWidth(100);
            depttable.getColumnModel().getColumn(4).setResizable(false);
            depttable.getColumnModel().getColumn(4).setPreferredWidth(180);
            depttable.getColumnModel().getColumn(5).setResizable(false);
            depttable.getColumnModel().getColumn(5).setPreferredWidth(100);
            depttable.getColumnModel().getColumn(6).setResizable(false);
            depttable.getColumnModel().getColumn(6).setPreferredWidth(100);
            depttable.getColumnModel().getColumn(7).setResizable(false);
            depttable.getColumnModel().getColumn(7).setPreferredWidth(100);
            depttable.getColumnModel().getColumn(8).setResizable(false);
            depttable.getColumnModel().getColumn(8).setPreferredWidth(180);
            depttable.getColumnModel().getColumn(9).setResizable(false);
            depttable.getColumnModel().getColumn(10).setResizable(false);
            depttable.getColumnModel().getColumn(10).setPreferredWidth(120);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 1150, 215));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medbackground_1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void quantityadviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityadviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityadviceActionPerformed

    private void pricecomponyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricecomponyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricecomponyActionPerformed

    private void depttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depttableMouseClicked
        int SelectedRow = depttable.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel) depttable.getModel();
        name2.setText(table.getValueAt(SelectedRow, 0).toString());
        dd2.setText(table.getValueAt(SelectedRow, 1).toString());
        ref2.setText(table.getValueAt(SelectedRow, 2).toString());
        dose2.setText(table.getValueAt(SelectedRow, 3).toString());
        sideeffects2.setText(table.getValueAt(SelectedRow, 4).toString());
        issue2.setText(table.getValueAt(SelectedRow, 5).toString());
        expiry2.setText(table.getValueAt(SelectedRow, 6).toString());
        compony2.setText(table.getValueAt(SelectedRow, 7).toString());
        advice2.setText(table.getValueAt(SelectedRow, 8).toString());
        price.setText(table.getValueAt(SelectedRow, 9).toString());
        quantity.setText(table.getValueAt(SelectedRow, 10).toString());
        
        jButton9.setEnabled(true);
    }//GEN-LAST:event_depttableMouseClicked

    private void jButton9jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9jButton5ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalmanagementsystem?useSSL=false", "root", "");
            PreparedStatement pst = conn.prepareStatement("UPDATE medicine SET name=?,dailydose=?,dose=?,sideeffects=?,issuedate=?,expirydate=?,componyname=?,storage=?,price=?,quantity=? WHERE refno=?");

            pst.setString(1, name2.getText());
            pst.setString(2, dd2.getText());
            pst.setString(3, dose2.getText());
            pst.setString(4, sideeffects2.getText());
            pst.setString(5, issue2.getText());
            pst.setString(6, expiry2.getText());
            pst.setString(7, compony2.getText());
            pst.setString(8, advice2.getText());
            pst.setString(9, price.getText());
            pst.setString(10, quantity.getText());
            pst.setString(11, ref2.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated Sucessfully");
            showTableData();
            
            name2.setText(null);
            dd2.setText(null);
            dose2.setText(null);
            sideeffects2.setText(null);
            issue2.setText(null);
            expiry2.setText(null);
            compony2.setText(null);
            advice2.setText(null);
            price.setText(null);
            quantity.setText(null);
            ref2.setText(null);
            jButton9.setEnabled(false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton9jButton5ActionPerformed

    private void jButton8jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8jButton4ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalmanagementsystem?useSSL=false", "root", "");
            PreparedStatement pst = conn.prepareStatement("delete from medicine where refno=?");
            pst.setString(1, ref2.getText());
            DefaultTableModel table = (DefaultTableModel) depttable.getModel();
            int SelectedRowIndex = depttable.getSelectedRow();
            table.removeRow(SelectedRowIndex);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Deleted Sucessfully");
            showTableData();
            name2.setText(null);
            dd2.setText(null);
            ref2.setText(null);
            dose2.setText(null);
            sideeffects2.setText(null);
            issue2.setText(null);
            expiry2.setText(null);
            compony2.setText(null);
            advice2.setText(null);
            price.setText(null);
            quantity.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please select a row from table you want to delete!");
        }
    }//GEN-LAST:event_jButton8jButton4ActionPerformed

    private void jButton3jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3jButton1ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalmanagementsystem?useSSL=false", "root", "");
            PreparedStatement pst = conn.prepareStatement("insert into medicine" + "(name,dailydose,refno,dose,sideeffects,issuedate,expirydate,componyname,storage,price,quantity)" + " values(?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, name2.getText());
            pst.setString(2, dd2.getText());
            pst.setString(3, ref2.getText());
            pst.setString(4, dose2.getText());
            pst.setString(5, sideeffects2.getText());
            pst.setString(6, issue2.getText());
            pst.setString(7, expiry2.getText());
            pst.setString(8, compony2.getText());
            pst.setString(9, advice2.getText());
            pst.setString(10, price.getText());
            pst.setString(11, quantity.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Medicine Added Sucessfully");
            showTableData();
            name2.setText(null);
            dd2.setText(null);
            ref2.setText(null);
            dose2.setText(null);
            sideeffects2.setText(null);
            issue2.setText(null);
            expiry2.setText(null);
            compony2.setText(null);
            advice2.setText(null);
            price.setText(null);
            quantity.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_jButton3jButton1ActionPerformed

    private void dd2ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dd2ddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dd2ddActionPerformed

    private void advice2adviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advice2adviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advice2adviceActionPerformed

    private void compony2componyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compony2componyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compony2componyActionPerformed

    private void expiry2expiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiry2expiryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiry2expiryActionPerformed

    private void issue2issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue2issueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issue2issueActionPerformed

    private void name2nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name2nameActionPerformed

    private void ref2refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ref2refActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ref2refActionPerformed

    private void dose2doseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dose2doseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dose2doseActionPerformed

    private void sideeffects2sideeffectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideeffects2sideeffectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sideeffects2sideeffectsActionPerformed

    private JFrame frame;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to Exit","Exit",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
//        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Index ap = new Index();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed
    public void showTableData() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalmanagementsystem?useSSL=false", "root", "");
            PreparedStatement pst = conn.prepareStatement("SELECT * FROM medicine");
            ResultSet rs = pst.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) depttable.getModel();
            tm.setRowCount(0);

            while (rs.next()) {
                Object o[] = {rs.getString("name"), rs.getString("dailydose"), rs.getInt("refno"), rs.getString("dose"), rs.getString("sideeffects"), rs.getString("issuedate"), rs.getString("expirydate"), rs.getString("componyname"), rs.getString("storage"), rs.getString("price"), rs.getString("quantity")};
                tm.addRow(o);
            }
//            depttable.setModel(DbUtils.resultSetToTableModel(rs));
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medicinedetails1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medicinedetails1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medicinedetails1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medicinedetails1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medicinedetails1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advice2;
    private javax.swing.JTextField compony2;
    private javax.swing.JTextField dd2;
    private javax.swing.JTable depttable;
    private javax.swing.JTextField dose2;
    private javax.swing.JTextField expiry2;
    private javax.swing.JTextField issue2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField name2;
    private javax.swing.JPanel panel2;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField ref2;
    private javax.swing.JTextField sideeffects2;
    // End of variables declaration//GEN-END:variables
}
